### ISSUE TITLE
Install FSF-04 sync server in VM

### ISSUE THREAD

**Issue by sighmon** [ACMILabs/media-player#171]
- [ ] Install the media-player sync server for `FSF-04` in a VM
- [ ] Set all `FSF-04-` devices to point to that server

## Details

At the moment Dan Von Sterner's `FSF-04` media wall is running from the [DD-00-AV10A](https://dashboard.balena-cloud.com/devices/b7c1c2917c84b9af70b934abb3572da4/summary)

That needs to be moved to somewhere more stable than my desk.

To set the clients in bulk:

```python
from exhibitions.models import Device, DeviceVariable
devices = Device.objects.filter(name__startswith='FSF-04-')
for device in devices:
    try:
        dv = DeviceVariable.objects.get(device=device, variable_type='EV', name='SYNC_CLIENT_TO')
        dv.value = '172.16.4.232'
        dv.save()
    except Exception as exception:
        print(f'Failed: {device}')

```

**Comment by framigni** [comment]
However, the exhibition team might want a more "portable" solution, e.g. the sync server is a physical hw that's installed in proximity of the wall (e.g the closer comms room). So if the wall needs to travel to a different location, it won't depend on ACMI on-premises platforms. Just to think about
