### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by Wallacedtn** [ACMILabs/media-player#178]
Sorry for my English. I don't know how to resolve this error.

Any suggestions?

obs.: I started to study programming a little while ago 
​
![image](https://user-images.githubusercontent.com/82247210/114254678-32644980-9987-11eb-859e-e0845a1a722e.png)

**Comment by sighmon** [comment]
@Wallacedtn Remove `print()` and it'll work. e.g. `str(round(4,5) * 100) + ' %'`

The exception occurs because the return class of a `print()` function is `NoneType`.

I'm closing this issue as it has nothing to do with our repo.
