### ISSUE TITLE
Spike: Improve frame synchronisation behaviour

### ISSUE THREAD

**Issue by dsamores** [ACMILabs/media-player#68]
VLC's time reporting is unreliable and therefore difficult to use as a basis as synchronisation messaging. Therefore, we've switched to an approach that uses a separate master clock and all vlc players are told to synchronise to that master clock. 

Even if a vlc player is at the correct time, we suspect that telling it to play from that correct time causes it a perceptible pause, so we want to minimise `set_time` calls. Therefore:

- Tell every player to start at the same time
- Trust playback will be within 1 frame thereafter
- Video-length seconds later do it again

**Comment by framigni** [comment]
I'd close this one, @sighmon , if you agree

**Comment by sighmon** [comment]
Brought to within ~20 ms by https://github.com/ACMILabs/media-player/issues/141
